# Development environment
version: '3.8'

services:
  front:
    image: node:14-alpine
    networks:
      - main
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: npm run dev -- --host 0.0.0.0

networks:
  main:
